### ISSUE TITLE
Expand to up ?

### ISSUE THREAD

**Issue by zahidcataltas** [saket/cascade#26] opened 2021-11-21 00:34 UTC
How do I make it open upwards when I click on a view at the bottom of the screen?

**Comment by saket** [comment] 2021-11-25 04:59
Is this a duplicate of https://github.com/saket/cascade/issues/21?

**Comment by zahidcataltas** [comment] 2021-11-25 13:06
I'm not sure.
Now like this:
![00](https://user-images.githubusercontent.com/23355390/143446980-7637f3ae-af0c-44b1-ba0b-7546b6b02003.gif)
I need:
![qq](https://user-images.githubusercontent.com/23355390/143447004-127b99f1-1d4b-4c6a-86ff-bb2580477a97.gif)

**Comment by zahidcataltas** [comment] 2021-11-25 13:11
And yes I guess same problem with #15  . Sorry for being repetitive.

**Comment by saket** [comment] 2023-10-25 17:11
Closing this in favor of #15.

**Closed as completed by saket** 2023-10-25 17:11 UTC
